/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: chatmessage.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "chatmessage.pb-c.h"
void   chat_app__message__init
                     (ChatApp__Message         *message)
{
  static const ChatApp__Message init_value = CHAT_APP__MESSAGE__INIT;
  *message = init_value;
}
size_t chat_app__message__get_packed_size
                     (const ChatApp__Message *message)
{
  assert(message->base.descriptor == &chat_app__message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat_app__message__pack
                     (const ChatApp__Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chat_app__message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat_app__message__pack_to_buffer
                     (const ChatApp__Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chat_app__message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChatApp__Message *
       chat_app__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChatApp__Message *)
     protobuf_c_message_unpack (&chat_app__message__descriptor,
                                allocator, len, data);
}
void   chat_app__message__free_unpacked
                     (ChatApp__Message *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chat_app__message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue chat_app__message__option__enum_values_by_number[3] =
{
  { "LISTCLIENTS", "CHAT_APP__MESSAGE__OPTION__LISTCLIENTS", 0 },
  { "CHAT", "CHAT_APP__MESSAGE__OPTION__CHAT", 1 },
  { "RESPONSE", "CHAT_APP__MESSAGE__OPTION__RESPONSE", 2 },
};
static const ProtobufCIntRange chat_app__message__option__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex chat_app__message__option__enum_values_by_name[3] =
{
  { "CHAT", 1 },
  { "LISTCLIENTS", 0 },
  { "RESPONSE", 2 },
};
const ProtobufCEnumDescriptor chat_app__message__option__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "chatApp.Message.Option",
  "Option",
  "ChatApp__Message__Option",
  "chatApp",
  3,
  chat_app__message__option__enum_values_by_number,
  3,
  chat_app__message__option__enum_values_by_name,
  1,
  chat_app__message__option__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ChatApp__Message__Option chat_app__message__opt__default_value = CHAT_APP__MESSAGE__OPTION__LISTCLIENTS;
static const ProtobufCFieldDescriptor chat_app__message__field_descriptors[6] =
{
  {
    "sourceIp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ChatApp__Message, sourceip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "destIp",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ChatApp__Message, destip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "messageLength",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ChatApp__Message, messagelength),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hostName",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ChatApp__Message, hostname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "textToSend",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ChatApp__Message, texttosend),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "opt",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ChatApp__Message, has_opt),
    offsetof(ChatApp__Message, opt),
    &chat_app__message__option__descriptor,
    &chat_app__message__opt__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat_app__message__field_indices_by_name[] = {
  1,   /* field[1] = destIp */
  3,   /* field[3] = hostName */
  2,   /* field[2] = messageLength */
  5,   /* field[5] = opt */
  0,   /* field[0] = sourceIp */
  4,   /* field[4] = textToSend */
};
static const ProtobufCIntRange chat_app__message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor chat_app__message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "chatApp.Message",
  "Message",
  "ChatApp__Message",
  "chatApp",
  sizeof(ChatApp__Message),
  6,
  chat_app__message__field_descriptors,
  chat_app__message__field_indices_by_name,
  1,  chat_app__message__number_ranges,
  (ProtobufCMessageInit) chat_app__message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
