CC = gcc
IPATH = /usr/local/include/
LIBPATH = /usr/local/lib/
BINPATH = bin
SOURCEPATH = src
PROTOBUF_GEN = chatmessage.pb-c

CFLAGS = -I $(IPATH) -L $(LIBPATH) -g -Wall
LFLAGS = -lprotobuf-c -pthread

SERVER_TARGET = chatserver
CLIENT_TARGET = chatclient

all: $(SERVER_TARGET) $(CLIENT_TARGET)

$(SERVER_TARGET): $(SOURCEPATH)/$(SERVER_TARGET).c
	$(CC) $(CFLAGS) $(SOURCEPATH)/$(PROTOBUF_GEN).c $(SOURCEPATH)/$(SERVER_TARGET).c -o $(BINPATH)/$(SERVER_TARGET) $(LFLAGS)

$(CLIENT_TARGET): $(SOURCEPATH)/$(CLIENT_TARGET).c
	$(CC) $(CFLAGS) $(SOURCEPATH)/$(PROTOBUF_GEN).c $(SOURCEPATH)/$(CLIENT_TARGET).c -o $(BINPATH)/$(CLIENT_TARGET) $(LFLAGS)

clean:
	rm $(BINPATH)/$(SERVER_TARGET)
	rm $(BINPATH)/$(CLIENT_TARGET)
