CC = gcc
INC_PATH = /usr/include/
LIBPATH = /usr/include/
BIN_PATH = bin
SOURCE_PATH = src
PROTOBUF_GEN = chatmessage.pb-c

CFLAGS=-I $(INC_PATH) -L $(LIBPATH) -g -Wall
LDFLAGS=-lprotobuf-c -pthread

SERVER_TARGET = chatserver
CLIENT_TARGET = chatclient

all: $(SERVER_TARGET) $(CLIENT_TARGET)

$(SERVER_TARGET): $(SOURCE_PATH)/$(SERVER_TARGET).c
	$(CC) $(CFLAGS) $(SOURCE_PATH)/$(PROTOBUF_GEN).c $(SOURCE_PATH)/$(SERVER_TARGET).c -o $(BIN_PATH)/$(SERVER_TARGET) $(LDFLAGS)

$(CLIENT_TARGET): $(SOURCE_PATH)/$(CLIENT_TARGET).c
	$(CC) $(CFLAGS) $(LDFLAGS) $(SOURCE_PATH)/$(PROTOBUF_GEN).c $(SOURCE_PATH)/$(CLIENT_TARGET).c -o $(BIN_PATH)/$(CLIENT_TARGET) $(LDFLAGS)

clean:
	rm $(BIN_PATH)/$(SERVER_TARGET)
	rm $(BIN_PATH)/$(CLIENT_TARGET)
